name: CI-CD_Intro
on:
  push:
    branches: 
      main
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Build project
        run: echo "Build project..."
  
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        run: echo "Starting test project..."
    
