name: CI-CD_Intro
on:
  push:
    branches: 
      main
jobs:
  build:
    runs-on: self-hosted  
    steps:
      - name: System name
        run: cat /etc/os-release
      - name: Kernel version
        run: uname -r
      - name: Docker version
        run: docker version
    
